/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_ABSTRACTSTUBSERVER_H_
#define JSONRPC_CPP_STUB_ABSTRACTSTUBSERVER_H_

#include <jsonrpccpp/server.h>

class AbstractStubServer : public jsonrpc::AbstractServer<AbstractStubServer>
{
    public:
        AbstractStubServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<AbstractStubServer>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("startTransfer", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_STRING, "bedNumber",jsonrpc::JSON_STRING,"clinicoreId",jsonrpc::JSON_STRING,"location",jsonrpc::JSON_STRING, NULL), &AbstractStubServer::startTransferI);
            this->bindAndAddNotification(jsonrpc::Procedure("notifyServer", jsonrpc::PARAMS_BY_NAME,  NULL), &AbstractStubServer::notifyServerI);
        }

        inline virtual void startTransferI(const Json::Value &request, Json::Value &response)
        {
            response = this->startTransfer(request["bedNumber"].asString(), request["clinicoreId"].asString(), request["location"].asString());
        }
        inline virtual void notifyServerI(const Json::Value &request)
        {
            (void)request;
            this->notifyServer();
        }
        virtual std::string startTransfer(const std::string& bedNumber, const std::string& clinicoreId, const std::string& location) = 0;
        virtual void notifyServer() = 0;
};

#endif //JSONRPC_CPP_STUB_ABSTRACTSTUBSERVER_H_
