/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_STUBCLIENT_H_
#define JSONRPC_CPP_STUB_STUBCLIENT_H_

#include <jsonrpccpp/client.h>

class StubClient : public jsonrpc::Client
{
    public:
        StubClient(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

        std::string startTransfer(const std::string& bedNumber, const std::string& clinicoreId, const std::string& location) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["bedNumber"] = bedNumber;
            p["clinicoreId"] = clinicoreId;
            p["location"] = location;
            Json::Value result = this->CallMethod("startTransfer",p);
            if (result.isString())
                return result.asString();
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        void notifyServer() throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p = Json::nullValue;
            this->CallNotification("notifyServer",p);
        }
};

#endif //JSONRPC_CPP_STUB_STUBCLIENT_H_
